version: 2.0
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:12
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Build
          command: yarn build
